site_name: Math Library
repo_url: https://github.com/yeahBOYYYYY/math-library/
repo_name: yeahBOYYYYY/math-library
site_description: A documentation site for my project.
site_author: Ron Mikhelman
site_url: https://yeahBOYYYYY.github.io/math-library/
copyright: Copyright &copy; 2024 - 2026 Ron Mikhelman

markdown_extensions:
  - toc:
      permalink: "🔗"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true  

theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

  icon:
    repo: fontawesome/brands/github
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to system preference

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - header.autohide

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yeahBOYYYYY
      name: GitHub

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/admonitions.css

nav:
  - Home: index.md
  - Mathematics Bachelor:
    - mathematics_bachelor/index.md
    - Discrete Mathematics:
      - Introduction to Set Theory: mathematics_bachelor/discrete_mathematics/introduction_to_set_theory.md
      - Introduction to Combinatorics and Graph Theory: mathematics_bachelor/discrete_mathematics/introduction_to_combinatorics_and_graph_theory.md
    - Analysis:
      - Real Analysis 1: mathematics_bachelor/analysis/real_analysis_1.md
      - Real Analysis 2: mathematics_bachelor/analysis/real_analysis_2.md
  - Computer Science Bachelor:
    - computer_science_bachelor/index.md
    - Algorithms:
      - Algorithms: computer_science_bachelor/algorithms/algorithms.md
      - Data Structures: computer_science_bachelor/algorithms/data_structures.md