site_name: Math Library
repo_url: https://github.com/yeahBOYYYYY/math-library/
repo_name: yeahBOYYYYY/math-library
site_description: A documentation site for my project.
site_author: Ron Mikhelman
site_url: https://yeahBOYYYYY.github.io/math-library/

nav:
  - Home: index.md
  - About: about.md
  - User Guide:
      - Installation: user-guide/configuration-options.md
      - Usage: user-guide/getting-started.md

markdown_extensions:
  - toc:
      permalink: ""

theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

  icon:
    repo: fontawesome/brands/github
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to system preference

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.share

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yeahBOYYYYY
      name: GitHub

copyright: Copyright &copy; 2024 - 2026 Ron Mikhelman